name: CI/CD for MkDocs with Mike

on:
  push:
    branches:
      - master # Déclencher le workflow sur les pushs vers la branche master

permissions:
  contents: write

jobs:
  deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupération du code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Python
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Étape 3 : Configuration du cache pour accélérer les builds
      - name: Configure Cache
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      # Étape 4 : Installation des dépendances
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install mike

      # Étape 5 : Configuration de Git
      - name: Configure Git User
        run: |
          git config --global user.name "Fast2docs"
          git config --global user.email "Fast2-docs@noreply.github.com"

      # Étape 6 : Récupérer les dernières modifications de la branche gh-pages
      - name: Pull Latest Changes from gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages

      # Étape 7 : Copier mkdocs.yml depuis la branche master vers gh-pages
      - name: Copy mkdocs.yml from master to gh-pages
        run: |
          git checkout master -- mkdocs.yml
          git add mkdocs.yml
          git commit -m "Add mkdocs.yml from master"
          git push origin gh-pages

      # Étape 8 : Déploiement de la documentation
      - name: Deploy Documentation with Mike
        run: mike deploy --push --update-aliases 2025.x.x latest

  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupération du code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Étape 2 : Vérification des liens Markdown
      - name: Check Markdown Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
