name: CI/CD for MkDocs with Mike

on:
  push:
    branches:
      - master # Trigger the workflow on pushes to the master branch

permissions:
  contents: write

jobs:
  deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Configure cache to speed up builds
      - name: Configure Cache
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install mike

      # Step 5: Configure Git user
      - name: Configure Git User
        run: |
          git config --global user.name "Fast2docs"
          git config --global user.email "Fast2-docs@noreply.github.com"

      # Step 6: Fetch the latest changes from the gh-pages branch
      #- name: Pull Latest Changes from gh-pages
      #run: |
      #git fetch origin gh-pages
      #git checkout gh-pages
      #git pull origin gh-pages

      # Step 7: Copy mkdocs.yml from master to gh-pages (only if modified)
      #- name: Copy mkdocs.yml from master to gh-pages
      #  run: |
      #    git checkout master -- mkdocs.yml
      #   Check if mkdocs.yml was modified before committing
      #   if git diff --exit-code mkdocs.yml; then
      #   echo "No changes to mkdocs.yml, skipping commit."
      #  else
      #    git add mkdocs.yml
      #   git commit -m "Add mkdocs.yml from master"
      #   git push origin gh-pages
      # fi

      # Step 8: Copy the docs directory from master to gh-pages (only if modified)
      #- name: Copy docs from master to gh-pages
      # run: |
      # git checkout master -- docs
      # Check if the docs directory has been modified before committing
      #  if git diff --exit-code docs; then
      #   echo "No changes to docs directory, skipping commit."
      # else
      #  git add docs
      # git commit -m "Add docs from master"
      #  git push origin gh-pages
      #fi

      # Step 9: Deploy documentation with Mike
      - name: Deploy Documentation with Mike
        run: mike deploy 2.x

  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Check Markdown links
      - name: Check Markdown Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
